[tool.poetry]
name = "openbb-cboe"
version = "1.1.3"
description = "CBOE extension for OpenBB"
authors = ["OpenBB Team <hello@openbb.co>"]
readme = "README.md"
packages = [{ include = "openbb_cboe" }]

[tool.poetry.dependencies]
python = "^3.8"
aiohttp-client-cache = "^0.10.0"
aiosqlite = "^0.19.0"
openbb-core = "^1.1.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."openbb_provider_extension"]
cboe = "openbb_cboe:cboe_provider"
