[tool.poetry]
name = "openbb-tradier"
version = "1.0.0"
description = "Tradier Provider Extension for the OpenBB Platform"
authors = ["OpenBB <hello@openbb.co>"]
readme = "README.md"
packages = [{ include = "openbb_tradier" }]

[tool.poetry.dependencies]
python = "^3.8"
openbb-core = "^1.1.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."openbb_provider_extension"]
tradier = "openbb_tradier:tradier_provider"
