name: Nightly Build

env:
  OPENBB_ENABLE_QUICK_EXIT: true
  OPENBB_LOG_COLLECT: false
  OPENBB_USE_PROMPT_TOOLKIT: false
  PIP_DEFAULT_TIMEOUT: 100
  OPENBB_FILE_OVERWRITE: true
  PYTHONNOUSERSITE: 1

on:
  schedule:
    - cron: "0 0 * * *"

permissions:
  actions: write

jobs:
  trigger-pypi-build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger PyPI Build
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          workflow: pypi-nightly.yml
          token: ${{ secrets.GITHUB_TOKEN }}

  trigger-api-integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Platform API Integration Test
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          workflow: platform-api-integration-test.yml
          token: ${{ secrets.GITHUB_TOKEN }}
